steps:
- script: |
    activate bayesian-modelling-tutorial
    mkdir -p docs/notebooks
    jupyter nbconvert --config nbconvert_config.py --execute --template full
    pandoc README.md -o docs/index.html -c static/pandoc.css -s
  displayName: 'Build docs pages'
