jobs:
  - job: macpy37
    variables:
      python.version: "3.7"
    pool:
      vmImage: macOS-10.14
    steps:
      - template: templates/conda-mac.yml
      - template: templates/setup-script.yml
      - template: templates/nb-docs.yml

  - job: macpy36
    variables:
      python.version: "3.6"
    pool:
      vmImage: macOS-10.14
    steps:
      - template: templates/conda-mac.yml
      - template: templates/setup-script.yml
      - template: templates/nb-docs.yml

  - job: linux
    strategy:
      matrix:
        py37:
          python.version: "3.7"
        py36:
          python.version: "3.6"
    variables:
      miniconda.url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    pool:
      vmImage: ubuntu-16.04
    steps:
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - template: templates/setup-script.yml
      - template: templates/nb-docs.yml