jobs:
  - job: macOS
    strategy: templates/python-matrix.yml
    variables:
      miniconda.url: https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    pool:
      vmImage: macOS-10.14
    steps:
      - template: templates/setup-script.yml
      - template: templates/nb-docs.yml

  - job: linux
    strategy: templates/python-matrix.yml
    variables:
      miniconda.url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: templats/setup-script.yml
      - template: templates/nb-docs.yml