jobs:
  - job: macOS
    strategy:
      matrix:
        py37:
          python.version: "3.7"
        py36:
          python.version: "3.6"
    variables:
      miniconda.url: https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    pool:
      vmImage: macOS-10.14
    steps:
      # Add conda to bash
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
      # We need to take ownership if we want to update conda or install packages globally
      - bash: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation
      - template: templates/setup-script.yml
      - template: templates/nb-docs.yml

  - job: linux
    strategy:
      matrix:
        py37:
          python.version: "3.7"
        py36:
          python.version: "3.6"
    variables:
      miniconda.url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    pool:
      vmImage: ubuntu-16.04
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - template: templates/setup-script.yml
      - template: templates/nb-docs.yml